apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- base # {"type":"string","x-kustomize":{"partialSetters":[{"name":"base-dir","value":"base"}]}}
- resources
patches:
- path: patches/cluster-patch.yaml
  target:
    kind: ContainerCluster
- path: patches/nodepool-patch.yaml
  target:
    kind: ContainerNodePool
